<?php
/*
    Sessions
    -session is stored on the server
    -session store only a user key in cookie to know its you
    -key are generated by php engine so its almost impossible to guess
    -you need to add it before any output
 */
session_start();

//$_SESSION['name'] = "ahmad";
//$_SESSION['id'] = 2039995;
//print_r($_SESSION);


//$_SESSION['name']= "zain";
//isset($_SESSION['views'])?$_SESSION['views']++ :$_SESSION['views']=1;
//echo"hello " .$_SESSION['name'] . " view count is ". $_SESSION['views'];
//echo '<a href="about.php">about</a>';

if($_SERVER["REQUEST_METHOD"] == "POST"){
    if ($_POST['user']=== 'yasmen'){
        $_SESSION['username'] = 'yaso';
        $_SESSION['id'] = 1500;
    }
}
echo '<pre>';
print_r($_SESSION);
echo '<pre>';
if (isset($_SESSION['username'])){
    echo"hello " .$_SESSION['username'] ;

}else{

    ?>
<form action="#" method="post">
    <input type="text" name="user">
    <input type="submit" value="login">
</form>
<?php }
?>

<a href="logout.php">logout</a>


